name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.18

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pytest
      run: |
        pip install pytest

    - name: Debug Test Discovery
      run: |
        ls -R tests/
        cat tests/test1.py
        python -m pytest tests/

    - name: Build and Test
      run: |
        python -m pytest tests/test_example.py  # Specify the directory where your tests are located

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build -t fastapi_endpoint .

    - name: Push Docker Image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag fastapi_endpoint:latest fastapi_endpoint:latest
        docker push fastapi_endpoint:latest
    - name: Deploy to Server (Replace with your deployment script)
      run: |
        ssh user@your-server "docker pull fastapi_endpoint:latest && docker-compose up -d"




